# Generated by Django 5.2.4 on 2025-08-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='output',
            new_name='expected_output',
        ),
        migrations.AddField(
            model_name='testcase',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Should this test case be visible to users?'),
        ),
    ]
