# Generated by Django 5.2.4 on 2025-08-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_rename_output_testcase_expected_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='template_code',
            field=models.TextField(blank=True, default='def solution(input):\n    # Write your code here\n    return', help_text='Initial code template to display in the editor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('javascript', 'JavaScript')], max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Runtime Error', 'Runtime Error')], max_length=20),
        ),
    ]
