# Generated by Django 5.2.4 on 2025-08-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='useranswer',
            name='is_auto_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
