# Generated by Django 5.2.4 on 2025-08-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('official_link', models.URLField()),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('skills', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('job_type', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('IN', 'Internship'), ('CN', 'Contract')], max_length=2)),
                ('work_mode', models.CharField(choices=[('R', 'Remote'), ('H', 'Hybrid'), ('O', 'On-site')], max_length=1)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('application_link', models.URLField()),
            ],
        ),
    ]
